### PR TITLE
Fix checkbox field when exporting users

### PR DESCRIPTION
**Pull request by stuartswan**
Exporting users with checkbox field data resulted in a blank column
data, this commit exports checkbox data correctly.

### CODE REVIEW

**Comment by boboldehampsink** [comment]
I don't get this fix. Why `foreach` through `$data` when it is NOT an array?

**Comment by stuartswan** [comment]
Good point, it still works for me, the data in the CMS appears as `["Item 1","Item 2"]` so already in array format?

When I export using my fix it shows as `Item 1, Item 2` which is the desired output.

Thanks

**Comment by boboldehampsink** [comment]
Can you dump `$data`, see if it's probably an `ArrayCollection` object or something the like?

**Comment by stuartswan** [comment]
Here is the dump of the $data:

`object(Craft\MultiOptionsFieldData)#484 (2) {
  ["_options":"Craft\MultiOptionsFieldData":private]=>
  array(4) {
    [0]=>
    object(Craft\OptionData)#507 (3) {
      ["label"]=>
      string(1) "A"
      ["value"]=>
      string(1) "A"
      ["selected"]=>
      bool(false)
    }
    [1]=>
    object(Craft\OptionData)#510 (3) {
      ["label"]=>
      string(1) "B"
      ["value"]=>
      string(1) "B"
      ["selected"]=>
      bool(false)
    }
    [2]=>
    object(Craft\OptionData)#509 (3) {
      ["label"]=>
      string(1) "C"
      ["value"]=>
      string(1) "C"
      ["selected"]=>
      bool(false)
    }
    [3]=>
    object(Craft\OptionData)#519 (3) {
      ["label"]=>
      string(1) "D"
      ["value"]=>
      string(1) "D"
      ["selected"]=>
      bool(false)
    }
  }
  ["storage":"ArrayObject":private]=>
  array(0) {
  }
}
`

Last part mentions storage as ArrayObject so perhaps this is what you're after?

Thanks

**Pull request closed without merging**
